language: objective-c
osx_image: xcode7
xcode_sdk: iphonesimulator8.4
before_install:
    - brew update
    - brew outdated xctool || brew upgrade xctool

script: xctool -workspace Ellis.xcworkspace -scheme Ellis test -sdk iphonesimulator